### ISSUE TITLE
Design Explorations: Discovering blocks via search

### ISSUE THREAD

**Issue by melchoyce** [WordPress/block-library#5]
How can people discover new blocks to install via search?

**Comment by melchoyce** [comment]
![Search](https://user-images.githubusercontent.com/2846578/58340956-1bf88780-7e1b-11e9-9251-936ffb68bf65.png)

Some questions:
- What block information should be displayed in the search results? We could do as little as icon, name, and author, or as much as we show in a plugin card (name, description, author, button, more details link, star rating, number of installations, last updated, compatibility). I'm leaning towards keeping it slim, and letting the majority of the details exist within the block details screen.
- How should someone get to the details screen? Should we include an explicit link, or should clicking on any part of the card open the details screen?
- How many results from the block directory should we show? I'm leaning towards no more than 5, pulling from the most relevant top results in the directory. We could include a link to view more results.
- Should you be able to add a block directly from the search results (Idea 5), or should you have to visit the details screen first?
- Anything missing?

**Comment by TimothyBJacobs** [comment]
I really like idea 3. Particularly how it is feels similar to the plugin cards. For me personally, I find the plugin author extremely helpful when deciding what plugin to use. Though perhaps that is a negative. I also pay attention to when a plugin has been last updated. Though, since these are just single blocks, perhaps that metric won't be as important.

> How many results from the block directory should we show? I'm leaning towards no more than 5, pulling from the most relevant top results in the directory. We could include a link to view more results.

I think a way to show more results would be very important. I frequently look through more than 5 plugins when I'm trying to find a plugin, and I think its likely that there will be far more candidates for a single block than there are plugins. ie I might look at a list of 10 or so candidates for a gallery plugin, but I can imagine dozens of slider blocks with different variations from different authors.

> Should you be able to add a block directly from the search results (Idea 5), or should you have to visit the details screen first?

I think people should be encouraged to look at the details so as not to install dozens of blocks only to end up using one.

**Comment by melchoyce** [comment]
> I think a way to show more results would be very important. I frequently look through more than 5 plugins when I'm trying to find a plugin, and I think its likely that there will be far more candidates for a single block than there are plugins. ie I might look at a list of 10 or so candidates for a gallery plugin, but I can imagine dozens of slider blocks with different variations from different authors.

Do you think you'd be annoyed if you got linked out to another screen for more results?

**Comment by TimothyBJacobs** [comment]
If on the other screen I was still able to select the block that I wanted to use, I don't think I'd be annoyed, but I'm not sure what that process would look like exactly.

**Comment by zeldman** [comment]
5 is the shiz. It’s fast *and* provides more in-depth info, if desired, at one click. Ding ding ding, we have a winner. 💯

**Comment by mapk** [comment]
> What block information should be displayed in the search results?

Because this is such a tight space, I believe the less, the better. As you've mentioned before, the Author feels like important information and so do the review stars. My first instinct is just the Author as in `Idea 5` above. The `+` icon works great because it's somewhat inline with the Gutenberg inserter icon although a bit different in usage. 

> How should someone get to the details screen?

In regards to number 5 above, I imagine clicking anything other than the `+` icon would give the user the details screen.

> How many results from the block directory should we show?

Limit it to 3 maybe? 3 always feels like a nice round number. People get an idea of what's being offered and do some quick scanning before jumping into more results.

> Should you be able to add a block directly from the search results (Idea 5), or should you have to visit the details screen first?

I like adding it directly from the results with a click.

**Comment by sarahmonster** [comment]
> What block information should be displayed in the search results? 

I'm a fan of keeping it slim. What is the most important information a user needs in order to evaluate whether it's what they're looking for? Our user research has indicated that a big part of how people choose things is social proof and/or referrals of some kind, so that might be worth keeping in mind.

Putting on my "typical user" hat, here's what I'd suggest:

- Icon: If this is a developer-provided icon, I'm not sure how immediately useful it would be. If it's a screenshot or image of the rendered block itself, it would be super useful and probably the only thing I'll really pay attention to when making my choice.
- Name: This provides some value, but far less than an image.
- Author: I'm pretty torn on this one. Community members may rely on this data and be able to contextualise it better than the average user. I'd probably avoid showing it.
- Description: Possibly useful, but if I want to read more I'll go to the details page. Let's leave it off.
- Star rating: This is social proof and I'd suspect most users rely pretty heavily on it.
- Number of installations: This is also social proof and I know I personally rely on it a great deal, but I'm not sure the average user does. Is this more or less valuable than a star rating? 
- Last updated: This provides some value but isn't important enough to show in a limited space.
- Compatibility: As a user, this means nothing to me... I don't know what version of WordPress I'm running. (This is actually largely true.)

It would be neat if there were a way to combine star ratings and number of installations, since these are more related than we think of them as—a plugin with a 4 star rating across 10,000 installs is better social proof than a plugin with a 5 star rating across 100 installs. Is there a way that we can use these metrics to help users make better decisions more easily?

> How should someone get to the details screen? Should we include an explicit link, or should clicking on any part of the card open the details screen?

I think we need an explicit link for accessibility reasons, but I do like having other parts of the card clickable. Users should be able to install from this screen, which probably necessitates two buttons (or rather, one big button and one smaller, less prominent link to more details). Linking up other parts of the card would be great if the design and arrangement of elements allows for it, and if users wouldn't accidentally end up going to the details page when they intend to install the block.

> How many results from the block directory should we show? 

What about starting with a manageable number (I'm picking 7 from a hat here) and then having an option to load more? If we were able to track how many people found what they wanted in the first 7 results, we could tweak it to more or less depending on what people need.

> Should you be able to add a block directly from the search results (Idea 5), or should you have to visit the details screen first?

If I know what I want, let me install it in a single click, please!

> Anything missing?

How are we ordering the search results? This may inform how many we want to show, and what sort of social proof (if any) users need to see up-front.

**Comment by melchoyce** [comment]
> It would be neat if there were a way to combine star ratings and number of installations, since these are more related than we think of them as—a plugin with a 4 star rating across 10,000 installs is better social proof than a plugin with a 5 star rating across 100 installs. Is there a way that we can use these metrics to help users make better decisions more easily?

This is a good idea — I need to think on it more. We'd also want it to work for both blocks and plugins.

> How are we ordering the search results? This may inform how many we want to show, and what sort of social proof (if any) users need to see up-front.

I figure we're using whatever algorithm plugins are already using — @tellyworth can you confirm?

Since @sarahmonster says 7 and @mapk says 3, I'm gonna do 5 and we can adjust once we start testing:

![image](https://user-images.githubusercontent.com/2846578/58892623-8ed7ed00-86bc-11e9-8374-c47717ec7909.png)

**Comment by tomjn** [comment]
QQ: If I were to middle click or open one of those blocks listed, e.g. right click and open in new tab on MetaSlider and SuperSlider so I could see them side by side in a new tab, where would I end up?
