### ISSUE TITLE
Design Explorations: Previewing a block

### ISSUE THREAD

**Issue by melchoyce** [WordPress/block-library#6]
How should blocks be previewed before installing?

**Comment by melchoyce** [comment]
A couple variations on the same general idea of previewing a block in the editor before installing:

![Preview](https://user-images.githubusercontent.com/2846578/58496811-9b05fc80-8148-11e9-9e92-593f4ae29509.png)

Questions:
- Should the preview show a "real" version of the block, with placeholders you can fill out, or should the preview only show a demo? 
- Should you be able to adjust the block settings (toolbar and sidebar), regardless of whether it's real content or a demo?
- Should we also include an "install" button in the block sidebar?
- What if you don't like this block, and want to preview a different block instead?
- When the preview isn't selected, how should we visually differentiate it from the rest of the content? Should we still show an "install" button?
- What should happen on the front-end?

**Comment by TimothyBJacobs** [comment]
I really like the simplicity of the idea 1, but still making it very clear that this is a preview, you need to install the block to keep it.

> Should the preview show a "real" version of the block, with placeholders you can fill out, or should the preview only show a demo?

> Should you be able to adjust the block settings (toolbar and sidebar), regardless of whether it's real content or a demo?

I think a preview of a block should be as close to the real block as technically possible.

> When the preview isn't selected, how should we visually differentiate it from the rest of the content? Should we still show an "install" button?

Perhaps a similar treatment that reusable blocks get? I think having the install button visible would be great.

I wonder what happens if you try to save while previewing a block?

**Comment by melchoyce** [comment]
> I wonder what happens if you try to save while previewing a block?

That relates to [another suggestion](https://github.com/WordPress/block-directory/issues/7#issuecomment-497429818):

> what if we hid the installation process, and just proceeded as if the block was already installed? Then, on update/publish, we install the block behind-the-scenes?

**Comment by sarahmonster** [comment]
Instead of a preview, have we considered instead an "immediate install + immediate undo" flow here? If implemented well, it could potentially help by:

- Isolating potential errors to the moment of user interaction, rather than pushing them to the publishing flow. 
- Keeping the publish flow more focussed on the action of publishing. 
- Facilitating ease of “trying on” a block whilst ensuring 1:1 parity with actual block functionality and appearance.

Pushing the installation process to the publishing flow is a nice idea if it works consistently and reliably, but if the block doesn't install, it means your post doesn't publish, which could definitely feel frustrating, and if I'm not able to fully configure the block in my content, I'm not going to want to press that publish button.
